### ISSUE TITLE
FRONT : Création de voyage 4/4

### ISSUE THREAD

**Issue by HighnKein** [InstitutG4/app-traveled#100]
![creation_voyage_4](https://user-images.githubusercontent.com/9964529/35401952-5d55d324-01fb-11e8-8d73-8d61af2ff749.png)

**Comment by Oceanwave6** [comment]
Mise à jour maquette.
![creation_voyage_4](https://user-images.githubusercontent.com/9129560/35514792-a21a4378-0507-11e8-8c95-639600ed0ad8.png)
