### ISSUE TITLE
Modifier un logement

### ISSUE THREAD

**Issue by HighnKein** [InstitutG4/app-traveled#114]
## EN TANT QUE 
Utilisateur 

## JE VEUX 
Modifier les champs 

## POUR 

- [ ] Ajouter un bouton modifier en haut à droite pour passer en modif les infos du logement 
- [ ] Pouvoir modifier les champs 
- [ ] Ajouter un bouton enregistrer

**Comment by Benbb96** [comment]
@HighnKein On est d'accord que c'est pour modifier un logement en particulier.
Il ne s'agit pas de modifier l'ordre des logements dans la liste ou autre ?
