### ISSUE TITLE
Ajouter / Modifier une dépense

### ISSUE THREAD

**Issue by HighnKein** [InstitutG4/app-traveled#126]
![36719800-6808f32c-1ba6-11e8-8dc0-eaf38265b012](https://user-images.githubusercontent.com/9964529/36719931-c199a616-1ba6-11e8-9eca-66526ee76872.png)

**Comment by Oceanwave6** [comment]
![ajout_modif_depense](https://user-images.githubusercontent.com/9129560/36719800-6808f32c-1ba6-11e8-8dc0-eaf38265b012.png)
