### ISSUE TITLE
FRONT : Supprimer un logement

### ISSUE THREAD

**Issue by the-smaug** [InstitutG4/app-traveled#133]
![36719599-c35f1950-1ba5-11e8-93a9-e75376135fb8](https://user-images.githubusercontent.com/9964529/36719948-d04a2492-1ba6-11e8-9f2d-3c488a2a8b9f.png)

**Comment by Oceanwave6** [comment]
![popup_suppression](https://user-images.githubusercontent.com/9129560/36719599-c35f1950-1ba5-11e8-93a9-e75376135fb8.png)
