### ISSUE TITLE
Détail d'un voyage

### ISSUE THREAD

**Issue by HighnKein** [InstitutG4/app-traveled#232]
## En tant que 
Utilisateur 

## Je veux 
Accéder aux infos d'un voyage 

- [ ] Afficher les infos basiques (ex : nom du voyage, dates, avatar des participants, et la couleur du theme.

**Comment by Benbb96** [comment]
J'ai passé 4h sur cette tâche.
On peut la considérer terminé mais je pense qu'elle peut encore être amélioré en mettant la liste des participants au voyage dans le store plutôt que dans le state (permet de réutiliser le code plus facilement)

**Comment by HighnKein** [comment]
parrot
