### ISSUE TITLE
Voir la liste des logements

### ISSUE THREAD

**Issue by HighnKein** [InstitutG4/app-traveled#240]
## En tant que 
Utilisateur 

## Je veux 
Accéder à la liste des logements du voyage 

- [ ] Créer la page "liste des logements"
- [ ] Afficher les logements dans l'ordre chronologique et groupé par date 
- [ ] Afficher les dates, le nom de l'hotel, l'adresse (qui est un lien qui l'ouvre dans un gps), les avatars des participants

**Comment by qreboli** [comment]
parrot
