### ISSUE TITLE
Liste des dépenses 2 (dépenses personnelles)

### ISSUE THREAD

**Issue by HighnKein** [InstitutG4/app-traveled#257]
## EN TANT QUE 
Utilisateur

## JE VEUX 
Voir combien des dépenses me concernent et combien j'ai dépensé depuis le début du voyage.

- [ ] Afficher la liste des dépenses me concernant 
- [ ] Sur les dépenses afficher l'impact du montant sur ma balance, le montant de la dépense et le nom de la dépense
- [ ] Afficher le total des dépenses me concernant uniquement

**Comment by qreboli** [comment]
parrot
