### ISSUE TITLE
Création voyage 3 (ajout participants)

### ISSUE THREAD

**Issue by HighnKein** [InstitutG4/app-traveled#279]
![7](https://user-images.githubusercontent.com/9129560/39124407-a2bdbe5a-46fb-11e8-8c1a-13c384c27b64.png)

Icônes : 
mail -  envelope 
fleches gauche - chevron-left
fleches droite - chevron-right

**Comment by Benbb96** [comment]
Sur cette maquette, je pense qu'il manque un bouton avec une croix à côté des adresses mail afin de supprimer une personne.
Et aussi un bouton ajouter lorsqu'on a fini d'écrire le mail à ajouter.

Question également : "Comment trouve-t-on l'avatar à afficher juste avec l'adresse mail ?"
