### ISSUE TITLE
Component : Side menu mamène

### ISSUE THREAD

**Issue by HighnKein** [InstitutG4/app-traveled#309]
- [ ] utiliser drawer
- [ ] faire les link 
- [ ] Faire les icones en sous components
![image.png](https://images.zenhubusercontent.com/59e08a1bb0222d5de47b8494/686d5123-8799-4e94-be31-d4b41b6d80b5)

**Comment by Benbb96** [comment]
La PR est passée mais il n'y a pas de link vers les pages des modules (comme il n'existe pas encore...)
