### ISSUE TITLE
FRONT : Création d'un voyage 2/4

### ISSUE THREAD

**Issue by HighnKein** [InstitutG4/app-traveled#98]
![ajout fonc](https://user-images.githubusercontent.com/9964529/36835205-c492fba2-1d35-11e8-9255-3c557e4121e5.png)

**Comment by Oceanwave6** [comment]
Mise à jour maquette.
![creation_voyage_2](https://user-images.githubusercontent.com/9129560/35514732-7b83ee4e-0507-11e8-8c10-955cc76d7953.png)
