### ISSUE TITLE
FRONT : Création d'un voyage 3/4

### ISSUE THREAD

**Issue by HighnKein** [InstitutG4/app-traveled#99]
![ajout personnes](https://user-images.githubusercontent.com/9964529/36835190-b4afbc84-1d35-11e8-92b4-802ee718e396.png)

**Comment by Oceanwave6** [comment]
Mise à jour maquette.
![creation_voyage_3](https://user-images.githubusercontent.com/9129560/35514760-9076cc18-0507-11e8-8350-81d3012e8f61.png)
